<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE us-patent-assignments [<!ELEMENT us-patent-assignments (action-key-code, transaction-date, patent-assignments)>
<!ATTLIST us-patent-assignments  dtd-version   CDATA  #IMPLIED
                                 date-produced CDATA  #IMPLIED>
<!ELEMENT action-key-code (#PCDATA)>
<!ELEMENT transaction-date (date)>
<!ELEMENT patent-assignments (data-available-code | patent-assignment+)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT data-available-code (#PCDATA)>
<!ELEMENT patent-assignment (assignment-record, patent-assignors, patent-assignees, patent-properties)>
<!ELEMENT assignment-record (reel-no, frame-no, last-update-date, purge-indicator, recorded-date, page-count?, correspondent, conveyance-text)>
<!ELEMENT patent-assignors (patent-assignor+)>
<!ELEMENT patent-assignees (patent-assignee+)>
<!ELEMENT patent-properties (patent-property+)>
<!ELEMENT reel-no (#PCDATA)>
<!ELEMENT frame-no (#PCDATA)>
<!ELEMENT last-update-date (date)>
<!ELEMENT purge-indicator (#PCDATA)>
<!ELEMENT recorded-date (date)>
<!ELEMENT page-count (#PCDATA)>
<!ELEMENT correspondent (name, address-1?, address-2?, address-3?, address-4?)>
<!ELEMENT conveyance-text (#PCDATA)>
<!ELEMENT patent-assignor (name, execution-date?, date-acknowledged?)>
<!ELEMENT patent-assignee (name, address-1?, address-2?, city?, state?, country-name?, postcode?)>
<!ELEMENT patent-property (document-id*, invention-title?)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name name-type (natural | legal)  #IMPLIED>
<!ELEMENT address-1 (#PCDATA)>
<!ELEMENT address-2 (#PCDATA)>
<!ELEMENT address-3 (#PCDATA)>
<!ELEMENT address-4 (#PCDATA)>
<!ELEMENT execution-date (date)>
<!ELEMENT date-acknowledged (date)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT country-name (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT document-id (country, doc-number, kind?, name?, date?)>
<!ELEMENT invention-title (#PCDATA | b | i | u | sup | sub)*>
<!ATTLIST invention-title  id   ID     #IMPLIED
                           lang CDATA  #REQUIRED>
<!ELEMENT country (#PCDATA)>
<!ELEMENT doc-number (#PCDATA)>
<!ELEMENT kind (#PCDATA)>
<!--bold formatting for text-->
<!ELEMENT b (#PCDATA | i | u | smallcaps)*>
<!--italic formatting for text-->
<!ELEMENT i (#PCDATA | b | u | smallcaps)*>
<!--underscore: style - single is default-->
<!ELEMENT u (#PCDATA | b | i | smallcaps)*>
<!ATTLIST u  style  (single | double | dash | dots )  'single' >
<!--superscripted text-->
<!ELEMENT sup (#PCDATA | b | u | i)*>
<!--subscripted text-->
<!ELEMENT sub (#PCDATA | b | u | i)*>
<!--small capitals-->
<!ELEMENT smallcaps (#PCDATA | b | u | i)*>
]>
<us-patent-assignments dtd-version="1.0" date-produced="20131101">
  <action-key-code>DA</action-key-code>
  <transaction-date>
    <date>20150209</date>
  </transaction-date>
  <patent-assignments>
    <patent-assignment>
      <assignment-record>
        <reel-no>13780</reel-no>
        <frame-no>85</frame-no>
        <last-update-date>
          <date>20150209</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20030225</date>
        </recorded-date>
        <page-count>2</page-count>
        <correspondent>
          <name>ROBERT O. FOX, ESQ.</name>
          <address-1>LUEDEKA, NEELY &amp; GRAHAM, P.C.</address-1>
          <address-2>P.O. BOX 1871</address-2>
          <address-3>KNOXVILLE, TN 37901</address-3>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>HALSTEAD, P. DAVID</name>
          <execution-date>
            <date>20030219</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>SOUTHERN IMPACT RESEARCH CENTER, LLC</name>
          <address-1>1817 AILOR AVENUE</address-1>
          <city>KNOXVILLE</city>
          <state>TENNESSEE</state>
          <postcode>37921</postcode>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09870334</doc-number>
            <kind>X0</kind>
            <date>20010530</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6532632</doc-number>
            <kind>B1</kind>
            <date>20030318</date>
          </document-id>
          <invention-title lang="en">BUCKLE</invention-title>
        </patent-property>
      </patent-properties>
    </patent-assignment>
    <patent-assignment>
      <assignment-record>
        <reel-no>18635</reel-no>
        <frame-no>972</frame-no>
        <last-update-date>
          <date>20150209</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20061215</date>
        </recorded-date>
        <page-count>8</page-count>
        <correspondent>
          <name>ELIZABETH PARSONS</name>
          <address-1>1825 EYE STREET, NW</address-1>
          <address-2>WASHINGTON, DC 20006</address-2>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>PHILIPS SEMICONDUCTORS INC.</name>
          <execution-date>
            <date>20061206</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>NXP B.V.</name>
          <address-1>HIGH TECH CAMPUS 60</address-1>
          <city>5656 AG EINDHOVEN</city>
          <country-name>NETHERLANDS</country-name>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>08142648</doc-number>
            <kind>X0</kind>
            <date>19931025</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>5450556</doc-number>
            <kind>B1</kind>
            <date>19950912</date>
          </document-id>
          <invention-title lang="en">VLIW PROCESSOR WHICH USES PATH INFORMATION GENERATED BY A BRANCH CONTROL UNIT TO INHIBIT OPERATIONS WHICH ARE NOT ON A CORRECT PATH</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>08425697</doc-number>
            <kind>X0</kind>
            <date>19950419</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>5692139</doc-number>
            <kind>B1</kind>
            <date>19971125</date>
          </document-id>
          <invention-title lang="en">VLIW PROCESSING DEVICE INCLUDING IMPROVED MEMORY FOR AVOIDING COLLISIONS WITHOUT AN EXCESSIVE NUMBER OF PORTS</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>08358127</doc-number>
            <kind>X0</kind>
            <date>19941216</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>5832202</doc-number>
            <kind>B1</kind>
            <date>19981103</date>
          </document-id>
          <invention-title lang="en">EXCEPTION RECOVERY IN A DATA PROCESSING SYSTEM</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>08366958</doc-number>
            <kind>X0</kind>
            <date>19941230</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6370623</doc-number>
            <kind>B1</kind>
            <date>20020409</date>
          </document-id>
          <invention-title lang="en">MULTIPORT REGISTER FILE TO ACCOMMODATE DATA OF DIFFERING LENGTHS</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>08648333</doc-number>
            <kind>X0</kind>
            <date>19960515</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6131152</doc-number>
            <kind>B1</kind>
            <date>20001010</date>
          </document-id>
          <invention-title lang="en">PLANAR CACHE LAYOUT AND INSTRUCTION STREAM THEREFOR</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>08649732</doc-number>
            <kind>X0</kind>
            <date>19960515</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>5862398</doc-number>
            <kind>B1</kind>
            <date>19990119</date>
          </document-id>
          <invention-title lang="en">COMPILER GENERATING SWIZZLED INSTRUCTIONS USABLE IN A SIMPLIFIED CACHE LAYOUT</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>08784643</doc-number>
            <kind>X0</kind>
            <date>19970121</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>5870614</doc-number>
            <kind>B1</kind>
            <date>19990209</date>
          </document-id>
          <invention-title lang="en">THERMOSTAT CONTROLS DSP'S TEMPERATURE BY EFFECTUATING THE DSP SWITCHING BETWEEN TASKS OF DIFFERENT COMPUTE-INTENSITY</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>08909273</doc-number>
            <kind>X0</kind>
            <date>19970811</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>5931939</doc-number>
            <kind>B1</kind>
            <date>19990803</date>
          </document-id>
          <invention-title lang="en">READ CROSSBAR ELIMINATION IN A VLIW PROCESSOR</invention-title>
        </patent-property>
      </patent-properties>
    </patent-assignment>
    <patent-assignment>
      <assignment-record>
        <reel-no>20745</reel-no>
        <frame-no>265</frame-no>
        <last-update-date>
          <date>20150209</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20080319</date>
        </recorded-date>
        <page-count>2</page-count>
        <correspondent>
          <name>ARTHUR R. CRAWFORD</name>
          <address-1>NIXON &amp; VANDERHYE P.C.</address-1>
          <address-2>901 NORTH GLEBE ROAD</address-2>
          <address-3>11TH FLOOR</address-3>
          <address-4>ARLINGTON, VA  22203</address-4>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>AFFAITATI, PIETRO</name>
          <execution-date>
            <date>20080310</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>FABBRI, ANDREA</name>
          <execution-date>
            <date>20080310</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>IMS S.R.L.</name>
          <address-1>VIA LAURENTINA, 169</address-1>
          <city>POMEZIA RM</city>
          <country-name>ITALY</country-name>
          <postcode>I-00040</postcode>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>11988161</doc-number>
            <kind>X0</kind>
            <date>20080319</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20090104094</doc-number>
            <kind>A1</kind>
            <date>20090423</date>
          </document-id>
          <invention-title lang="en">Cold Sterilizer</invention-title>
        </patent-property>
      </patent-properties>
    </patent-assignment>
    <patent-assignment>
      <assignment-record>
        <reel-no>20763</reel-no>
        <frame-no>171</frame-no>
        <last-update-date>
          <date>20150209</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20080404</date>
        </recorded-date>
        <page-count>4</page-count>
        <correspondent>
          <name>STAAS &amp; HALSEY LLP</name>
          <address-1>ATTENTION: GENE M. GARNER, II</address-1>
          <address-2>1201 NEW YORK AVE., N.W., 7TH FLOOR</address-2>
          <address-3>WASHINGTON, D.C. 20005</address-3>
        </correspondent>
        <conveyance-text>CORRECTIVE ASSIGNMENT TO CORRECT THE THIRD INVENTOR PREVIOUSLY RECORDED AT REEL 019694 FRAME 0741. THE ASSIGNOR'S HEREBY CONFIRM THE ASSIGNMENT OF THE ENTIRE INTEREST(SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>JANG, GILJIN</name>
          <execution-date>
            <date>20070725</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>KIM, JEONGSU</name>
          <execution-date>
            <date>20070725</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>BRIDLE, JOHN S.</name>
          <execution-date>
            <date>20070725</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>HUNT, MELVYN J.</name>
          <execution-date>
            <date>20070725</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>SAMSUNG ELECTRONICS CO., LTD.</name>
          <address-1>416, MAETAN-DONG, YEONGTONG-GU</address-1>
          <city>SUWON-SI, GYEONGGI-DO 443-742</city>
          <country-name>KOREA, REPUBLIC OF</country-name>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>11882444</doc-number>
            <kind>X0</kind>
            <date>20070801</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20080033723</doc-number>
            <kind>A1</kind>
            <date>20080207</date>
          </document-id>
          <invention-title lang="en">METHOD, MEDIUM, AND SYSTEM DETECTING SPEECH USING ENERGY LEVELS OF SPEECH FRAMES</invention-title>
        </patent-property>
      </patent-properties>
    </patent-assignment>
    <patent-assignment>
      <assignment-record>
        <reel-no>22522</reel-no>
        <frame-no>240</frame-no>
        <last-update-date>
          <date>20150209</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20090408</date>
        </recorded-date>
        <page-count>7</page-count>
        <correspondent>
          <name>TIMOTHY J. OYER</name>
          <address-1>600 ATLANTIC AVENUE</address-1>
          <address-2>BOSTON, MA 02210</address-2>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>HOUSE, KURT</name>
          <execution-date>
            <date>20090214</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>AZIZ, MICHAEL J.</name>
          <execution-date>
            <date>20090130</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>SCHRAG, DANIEL PAUL</name>
          <execution-date>
            <date>20090408</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>PRESIDENT AND FELLOWS OF HARVARD COLLEGE</name>
          <address-1>17 QUINCY STREET</address-1>
          <city>CAMBRIDGE</city>
          <state>MASSACHUSETTS</state>
          <postcode>02138</postcode>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>12266632</doc-number>
            <kind>X0</kind>
            <date>20081107</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20100116443</doc-number>
            <kind>A1</kind>
            <date>20100513</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>8016016</doc-number>
            <kind>B2</kind>
            <date>20110913</date>
          </document-id>
          <invention-title lang="en">TROUGH SHADE SYSTEM AND METHOD</invention-title>
        </patent-property>
      </patent-properties>
    </patent-assignment>
    <patent-assignment>
      <assignment-record>
        <reel-no>34882</reel-no>
        <frame-no>425</frame-no>
        <last-update-date>
          <date>20150209</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20150204</date>
        </recorded-date>
        <page-count>3</page-count>
        <correspondent>
          <name>ANTHONY G. FUSSNER</name>
          <address-1>7700 BONHOMME</address-1>
          <address-2>SUITE 400</address-2>
          <address-3>ST. LOUIS, MO 63105</address-3>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>GRESKO, JOHNNY J.</name>
          <execution-date>
            <date>20150203</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>DIRECT SOUND HEADPHONES, LLC</name>
          <address-1>4405 MERAMEC BOTTOM RD.</address-1>
          <city>ST. LOUIS</city>
          <state>MISSOURI</state>
          <postcode>63129</postcode>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>11333176</doc-number>
            <kind>X0</kind>
            <date>20060117</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>7853034</doc-number>
            <kind>B1</kind>
            <date>20101214</date>
          </document-id>
          <invention-title lang="en">AMBIENT NOISE ISOLATION AUDIO HEADPHONES HAVING A LAYERED DAMPENING STRUCTURE</invention-title>
        </patent-property>
      </patent-properties>
    </patent-assignment>
    <patent-assignment>
      <assignment-record>
        <reel-no>34895</reel-no>
        <frame-no>362</frame-no>
        <last-update-date>
          <date>20150209</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20150127</date>
        </recorded-date>
        <page-count>5</page-count>
        <correspondent>
          <name>ANSEL M. SCHWARTZ, ATTORNEY AT LAW</name>
          <address-1>201 N. CRAIG STREET</address-1>
          <address-2>SUITE 304</address-2>
          <address-3>PITTSBURGH, PA  15213</address-3>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>NANOPHORETICS, LLC</name>
          <execution-date>
            <date>20150123</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>DICKERSON, SAMUEL J.</name>
          <address-1>56 ROSTOCK STREET</address-1>
          <city>PITTSBURGH</city>
          <state>PENNSYLVANIA</state>
          <postcode>15212</postcode>
        </patent-assignee>
        <patent-assignee>
          <name>CHIARULLI, DONALD M.</name>
          <address-1>17 CHAPEL RIDGE ROAD</address-1>
          <city>PITTSBURGH</city>
          <state>PENNSYLVANIA</state>
          <postcode>15238</postcode>
        </patent-assignee>
        <patent-assignee>
          <name>LEVITAN, STEVEN P.</name>
          <address-1>630 S. NEGLEY AVENUE</address-1>
          <city>PITTSBURGH</city>
          <state>PENNSYLVANIA</state>
          <postcode>15232</postcode>
        </patent-assignee>
        <patent-assignee>
          <name>CARTHEL, CRAIG</name>
          <address-1>521 SE 18TH AVENUE</address-1>
          <city>PORTLAND</city>
          <state>OREGON</state>
          <postcode>97214</postcode>
        </patent-assignee>
        <patent-assignee>
          <name>CORALUPPI, STEFANO</name>
          <address-1>258 NEVADA STREET</address-1>
          <city>NEWTON</city>
          <state>MASSACHUSETTS</state>
          <postcode>02460</postcode>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>14295934</doc-number>
            <kind>X0</kind>
            <date>20140604</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20140367260</doc-number>
            <kind>A1</kind>
            <date>20141218</date>
          </document-id>
          <invention-title lang="en">Method and Apparatus for Identifying Objects in a Plurality of Objects Using Dielectrophoresis</invention-title>
        </patent-property>
      </patent-properties>
    </patent-assignment>
    <patent-assignment>
      <assignment-record>
        <reel-no>34895</reel-no>
        <frame-no>488</frame-no>
        <last-update-date>
          <date>20150209</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20150128</date>
        </recorded-date>
        <page-count>2</page-count>
        <correspondent>
          <name>DAVID CARRITHERS</name>
          <address-1>CARRITHERS LAW OFFICE PLLC</address-1>
          <address-2>120 W. STEPHEN FOSTER AVENUE</address-2>
          <address-3>SUITE 101</address-3>
          <address-4>BARDSTOWN, KENTUCKY  40004</address-4>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>BULI, TIMMONS</name>
          <execution-date>
            <date>20140718</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>ANDERSON WOOD PRODUCTS COMPANY</name>
          <address-1>P.O. BOX 11517</address-1>
          <address-2>1381 BEECH STREET</address-2>
          <city>LOUISVILLE</city>
          <state>KENTUCKY</state>
          <postcode>40251</postcode>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>14120656</doc-number>
            <kind>X0</kind>
            <date>20140612</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20150014618</doc-number>
            <kind>A1</kind>
            <date>20150115</date>
          </document-id>
          <invention-title lang="en">Engineered wood handrail</invention-title>
        </patent-property>
      </patent-properties>
    </patent-assignment>
    <patent-assignment>
      <assignment-record>
        <reel-no>34902</reel-no>
        <frame-no>125</frame-no>
        <last-update-date>
          <date>20150209</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20150205</date>
        </recorded-date>
        <page-count>28</page-count>
        <correspondent>
          <name>BAO TRAN</name>
          <address-1>PO BOX 68</address-1>
          <address-2>SARATOGA, CA 95071</address-2>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>2PHASE TECHNOLOGIES INC.</name>
          <execution-date>
            <date>20130220</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>TRAN, BAO</name>
          <address-1>PO BOX 68</address-1>
          <city>SARATOGA</city>
          <state>CALIFORNIA</state>
          <postcode>95071</postcode>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>10824333</doc-number>
            <kind>X0</kind>
            <date>20040413</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20050035477</doc-number>
            <kind>A1</kind>
            <date>20050217</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>7172714</doc-number>
            <kind>B2</kind>
            <date>20070206</date>
          </document-id>
          <invention-title lang="en">USE OF STATE-CHANGE MATERIALS IN REFORMABLE SHAPES, TEMPLATES OR TOOLING</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>10150747</doc-number>
            <kind>X0</kind>
            <date>20020517</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20020195220</doc-number>
            <kind>A1</kind>
            <date>20021226</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6780352</doc-number>
            <kind>B2</kind>
            <date>20040824</date>
          </document-id>
          <invention-title lang="en">USE OF STATE-CHANGE MATERIALS IN REFORMABLE SHAPES, TEMPLATES OR TOOLING</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>11567152</doc-number>
            <kind>X0</kind>
            <date>20061205</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20070187855</doc-number>
            <kind>A1</kind>
            <date>20070816</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>7402265</doc-number>
            <kind>B2</kind>
            <date>20080722</date>
          </document-id>
          <invention-title lang="en">USE OF STATE-CHANGE MATERIALS IN REFORMABLE SHAPES, TEMPLATES OR TOOLING</invention-title>
        </patent-property>
      </patent-properties>
    </patent-assignment>
    <patent-assignment>
      <assignment-record>
        <reel-no>34902</reel-no>
        <frame-no>158</frame-no>
        <last-update-date>
          <date>20150209</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20150205</date>
        </recorded-date>
        <page-count>5</page-count>
        <correspondent>
          <name>LOUIS M HEIDELBERGER</name>
          <address-1>350 E. 79TH ST. APT 31C</address-1>
          <address-2>NEW YORK, NY 10075</address-2>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>GILMOUR INNOVATIONS LLC</name>
          <execution-date>
            <date>20141212</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>CERINET USA, INC.</name>
          <address-1>620 MARSHALL ST.</address-1>
          <city>LEXINGTON</city>
          <state>VIRGINIA</state>
          <postcode>24430</postcode>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>10917433</doc-number>
            <kind>X0</kind>
            <date>20040811</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20050007885</doc-number>
            <kind>A1</kind>
            <date>20050113</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>7234010</doc-number>
            <kind>B2</kind>